// Fetches mistlib (MISTLIB_REPO/MISTLIB_REF from .env), builds the wasm
// package with wasm-pack, and vendors the release artifacts into
// src/vendor/mistlib-wasm/. Runs automatically before dev/build; when
// MISTLIB_REPO is not configured it exits quietly because the vendored
// artifacts are committed and the app works without a rebuild.
//
// The source repository URL is intentionally NOT hardcoded — it is a private
// repo and this file may live in a public repository. Set MISTLIB_REPO in
// .env (gitignored) or in the environment.
import { existsSync, mkdirSync, rmSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const envPath = path.join(rootDir, ".env");
if (existsSync(envPath)) {
  process.loadEnvFile(envPath);
}

const repo = process.env.MISTLIB_REPO;
const ref = process.env.MISTLIB_REF || "develop";
const subdir = process.env.MISTLIB_SUBDIR || "mistlib-wasm";

if (!repo) {
  console.log("fetch-mistlib: MISTLIB_REPO not set — using the committed vendored build. Copy .env.example to .env to enable auto-fetch.");
  process.exit(0);
}

const cacheDir = path.join(rootDir, ".mistlib-src");
const vendorDir = path.join(rootDir, "src", "vendor", "mistlib-wasm");
const buildInfoPath = path.join(vendorDir, "BUILD_INFO.txt");

function run(cmd, args, cwd, extraEnv) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, {
    cwd,
    stdio: "inherit",
    env: extraEnv ? { ...process.env, ...extraEnv } : process.env,
  });
}

// Network failures (offline, DNS hiccups) must not block dev/build — the
// vendored artifacts are committed, so fall back to them with a warning.
try {
  if (!existsSync(path.join(cacheDir, ".git"))) {
    rmSync(cacheDir, { recursive: true, force: true });
    run("git", ["clone", repo, cacheDir]);
  }
  run("git", ["fetch", "origin", ref], cacheDir);
} catch (err) {
  if (existsSync(path.join(vendorDir, "mistlib_wasm.js"))) {
    console.warn(`fetch-mistlib: could not reach ${ref} (${err.message.trim()}) — using the existing vendored build`);
    process.exit(0);
  }
  throw err;
}
run("git", ["checkout", "FETCH_HEAD"], cacheDir);

// Skip the rebuild + re-vendor when the vendored output already comes from
// this exact commit — wasm-pack output is not byte-reproducible, so an
// unconditional rebuild dirties src/vendor/mistlib-wasm on every run.
const commit = execFileSync("git", ["rev-parse", "HEAD"], { cwd: cacheDir })
  .toString()
  .trim();
if (existsSync(buildInfoPath)) {
  const vendored = readFileSync(buildInfoPath, "utf8").match(/^commit:\s*([0-9a-f]{40})/m);
  if (vendored && vendored[1] === commit) {
    console.log(`mistlib (${ref} @ ${commit.slice(0, 12)}) already vendored — skipping build`);
    process.exit(0);
  }
}

const wasmCrateDir = path.join(cacheDir, subdir);
const wasmPackBin = process.platform === "win32" ? "wasm-pack.exe" : "wasm-pack";
// Remap the builder's home directory in embedded rustc debug paths so the
// committed wasm never leaks the local username (checked before vendoring).
run(wasmPackBin, ["build", "--target", "web", "--release"], wasmCrateDir, {
  RUSTFLAGS: [process.env.RUSTFLAGS, `--remap-path-prefix=${os.homedir()}=/build`]
    .filter(Boolean)
    .join(" "),
});

const pkgDir = path.join(wasmCrateDir, "pkg");
const builtWasm = readFileSync(path.join(pkgDir, "mistlib_wasm_bg.wasm"));
const homeToken = path.basename(os.homedir());
if (builtWasm.includes(Buffer.from(`\\Users\\${homeToken}`)) || builtWasm.includes(Buffer.from(`/home/${homeToken}`))) {
  console.error(`Built wasm embeds the local username (${homeToken}) — refusing to vendor it.`);
  process.exit(1);
}

mkdirSync(vendorDir, { recursive: true });
for (const f of ["mistlib_wasm.js", "mistlib_wasm.d.ts", "mistlib_wasm_bg.wasm", "mistlib_wasm_bg.wasm.d.ts"]) {
  copyFileSync(path.join(pkgDir, f), path.join(vendorDir, f));
}

// Record provenance so it's clear which commit produced these artifacts.
// The source repo URL is deliberately omitted so it does not get committed
// (private repo / possibly public vendor location).
writeFileSync(
  buildInfoPath,
  [
    "Generated by scripts/fetch-mistlib.mjs — do not edit by hand.",
    `ref:    ${ref}`,
    `commit: ${commit}`,
    `built:  ${new Date().toISOString().replace(/\.\d+Z$/, "Z")}`,
    "",
  ].join("\n"),
);

console.log(`mistlib (${ref}) built and vendored into src/vendor/mistlib-wasm @ ${commit.slice(0, 12)}`);
